# permissions for end users to edit kredis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kredis-operator
    app.kubernetes.io/managed-by: kustomize
  name: kredis-editor-role
rules:
- apiGroups:
  - stable.docker.direa.synology.me
  resources:
  - kredis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.docker.direa.synology.me
  resources:
  - kredis/status
  verbs:
  - get
