apiVersion: stable.docker.direa.synology.me/v1alpha1
kind: KRedis
metadata:
  labels:
    app.kubernetes.io/name: kredis-operator
    app.kubernetes.io/managed-by: kustomize
  name: kredis-sample
spec:
  replicas: 1 # 슬레이브 노드
  masters: 2 # 마스터 노드
  image: docker.direa.synology.me/redis-cluster:latest
  memory: 1gb
  basePort: 10000
  resource:
    requests:
      cpu: "2"
      memory: "2000Mi"
  secretName: "docker-secret"
