apiVersion: stable.docker.direa.synology.me/v1alpha1
kind: KRedis
metadata:
  labels:
    app.kubernetes.io/name: kredis-operator
    app.kubernetes.io/managed-by: kustomize
  name: kredis-sample
spec:
  replicas: 1 # 슬레이브 노드
  masters: 2 # 마스터 노드
  image: docker.direa.synology.me/redis-cluster:latest
  memory: 1gb
  basePort: 10000
  resource:
    limits:
      cpu: "4"       # CPU 제한량 e.g., 1, 500m, etc.
      memory: "8Gi"  # 메모리 제한량 e.g., 1Gi, 512Mi
    requests:
      cpu: "500m"    # CPU 요청량
      memory: "512Mi" # 메모리 요청량
  secretName: "docker-secret"
