apiVersion: stable.docker.direa.synology.me/v1alpha1
kind: KRedis
metadata:
  labels:
    app.kubernetes.io/name: kredis-operator
    app.kubernetes.io/managed-by: kustomize
  name: kredis-sample
spec:
  # TODO(user): Add fields here
